:mod:`spark_auto_mapper_fhir.value_sets.response_type`
======================================================

.. py:module:: spark_auto_mapper_fhir.value_sets.response_type


Module Contents
---------------

Classes
~~~~~~~

.. autoapisummary::

   spark_auto_mapper_fhir.value_sets.response_type.ResponseTypeCode
   spark_auto_mapper_fhir.value_sets.response_type.ResponseTypeCodeValues



.. class:: ResponseTypeCode(value: spark_auto_mapper.type_definitions.defined_types.AutoMapperTextInputType)


   Bases: :class:`spark_auto_mapper_fhir.value_sets.generic_type.GenericTypeCode`

   ResponseType
   From: http://hl7.org/fhir/response-code in valuesets.xml
       The kind of response to a message.

   .. attribute:: codeset
      :annotation: :FhirUri = http://hl7.org/fhir/response-code

      


.. class:: ResponseTypeCodeValues

   The message was accepted and processed without error.
   From: http://hl7.org/fhir/response-code in valuesets.xml

   .. attribute:: OK
      

      Some internal unexpected error occurred - wait and try again. Note - this is
      usually used for things like database unavailable, which may be expected to
      resolve, though human intervention may be required.
      From: http://hl7.org/fhir/response-code in valuesets.xml


   .. attribute:: TransientError
      

      The message was rejected because of a problem with the content. There is no
      point in re-sending without change. The response narrative SHALL describe the
      issue.
      From: http://hl7.org/fhir/response-code in valuesets.xml


   .. attribute:: FatalError
      

      


